name: Windows_vm

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "0912093366fekadu" -Force)
        run: Get-LocalUser -Name "Administrator" | Enable-LocalUser 
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        run: tar xf ngrok.zip
        run: Copy ngrok.exe C:\Windows\System32
        run: cmd /c echo ./ngrok.exe authtoken "2DetjXzq5SSZAGvMo4IIxQhUzgD_7AGzFSrj7NV6cS8CCUTcN" >a.ps1
        run: cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
        run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
        run: .\a.ps1
